<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DepartamentoCongreso;

class DepartamentosCongresoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $departamentos = [
            ["name" => "Almacén","extension"=>""],
            ["name" => "Análisis y Diseño de Sistemas", "extension"=>""],
            ["name" => "Archivo", "extension"=>""],
            ["name" => "Asesores de MORENA", "extension"=>""],
            ["name" => "Asesores Grupo Legislativo PAN", "extension"=>""],
            ["name" => "Asesores PRI", "extension"=>""],
            ["name" => "Ayudantía", "extension"=>""],
            ["name" => "Com. Social MORENA", "extension"=>""],
            ["name" => "Coordinación de Archivo, Biblioteca y Hemeroteca", "extension"=>""],
            ["name" => "Coordinación de Comunicación Social", "extension"=>""],
            ["name" => "Coordinación de Informática", "extension"=>""],
            ["name" => "Coordinación de Investigaciones Legislativas", "extension"=>""],
            ["name" => "Departamento de Adquisiciones", "extension"=>""],
            ["name" => "Departamento de Amparos", "extension"=>""],
            ["name" => "Departamento de Asistencia a Comisiones", "extension"=>""],
            ["name" => "Departamento de Asistencia a Sesiones", "extension"=>""],
            ["name" => "Departamento de Auditoría y Análisis de la Cuenta Pública", "extension"=>""],
            ["name" => "Departamento de Caja", "extension"=>""],
            ["name" => "Departamento de Capacitación, Asesoría, Revisión y Supervisión Legislativa", "extension"=>""],
            ["name" => "Departamento de Contabilidad", "extension"=>""],
            ["name" => "Departamento de Control de Personal", "extension"=>""],
            ["name" => "Departamento de Diario de los Debates", "extension"=>""],
            ["name" => "Departamento de Finanzas", "extension"=>""],
            ["name" => "Departamento de Fundo Legal", "extension"=>""],
            ["name" => "Departamento de Nómina", "extension"=>""],
            ["name" => "Departamento de Organización y Métodos", "extension"=>""],
            ["name" => "Departamento de Programación y Presupuesto", "extension"=>""],
            ["name" => "Departamento de Recursos Materiales", "extension"=>""],
            ["name" => "Departamento de Registro de Deuda Pública y Programas Federales", "extension"=>""],
            ["name" => "Departamento de Registro Documental Legislativo", "extension"=>""],
            ["name" => "Departamento de Responsabilidades Administrativas y Contrataciones Públicas", "extension"=>""],
            ["name" => "Departamento de Servicios Generales", "extension"=>""],
            ["name" => "Dip. Adrián Sigfrido Ávila Estrada", "extension"=>""],
            ["name" => "Dip. Alejandro Porras Marín", "extension"=>""],
            ["name" => "Dip. Ana Rosa Valdés Salazar", "extension"=>""],
            ["name" => "Dip. Angélica Peña Martínez", "extension"=>""],
            ["name" => "Dip. Antonio Ballesteros Grayeb", "extension"=>""],
            ["name" => "Dip. Astrid Sánchez Moguel", "extension"=>""],
            ["name" => "Dip. Baruch García Bocarando", "extension"=>""],
            ["name" => "Dip. Bertha Rosalia Ahued Malpica", "extension"=>""],
            ["name" => "Dip. Carlos Marcelo Ruiz Sánchez", "extension"=>""],
            ["name" => "Dip. Daniel Cortina Martínez", "extension"=>""],
            ["name" => "Dip. Daniela Flores Barnils", "extension"=>""],
            ["name" => "Dip. Diego Castañeda Aburto", "extension"=>""],
            ["name" => "Dip. Dorheny García Cayetano", "extension"=>""],
            ["name" => "Dip. Dulce María Hernández Tepole", "extension"=>""],
            ["name" => "Dip. Elena Córdova Molina", "extension"=>""],
            ["name" => "Dip. Elisa Mohedano Orellán", "extension"=>""],
            ["name" => "Dip. Elizabeth Martínez Marie", "extension"=>""],
            ["name" => "Dip. Elizabeth Morales García", "extension"=>""],
            ["name" => "Dip. Elvia Merlin Castro", "extension"=>""],
            ["name" => "Dip. Enrique Cambranis Torres ", "extension"=>""],
            ["name" => "Dip. Esteban Bautista Hernández", "extension"=>""],
            ["name" => "Dip. Estefanía Bastida Cuevas", "extension"=>""],
            ["name" => "Dip. Felipe Pineda Barradas", "extension"=>""],
            ["name" => "Dip. Fernando Yunes Márquez", "extension"=>""],
            ["name" => "Dip. Guadalupe Vázquez González", "extension"=>""],
            ["name" => "Dip. Héctor Yunes Landa", "extension"=>""],
            ["name" => "Dip. Imelda Garrido Alvarado", "extension"=>""],
            ["name" => "Dip. Indira de Jesús Rosales San Román", "extension"=>""],
            ["name" => "Dip. Ingrid Jeny Calderón Domínguez", "extension"=>""],
            ["name" => "Dip. Iris Orquídea Ortiz Carlos", "extension"=>""],
            ["name" => "Dip. Ivonne Selene Durán López", "extension"=>""],
            ["name" => "Dip. Janeth Adanely Rodríguez Rodríguez", "extension"=>""],
            ["name" => "Dip. Janix Liliana Castro Muñoz", "extension"=>""],
            ["name" => "Dip. José Reveriano Marín Hernández", "extension"=>""],
            ["name" => "Dip. José Ricardo Ruiz Carmona", "extension"=>""],
            ["name" => "Dip. Juan Morales Almora", "extension"=>""],
            ["name" => "Dip. Juan Tress Zilli", "extension"=>""],
            ["name" => "Dip. Liud Herrera Félix", "extension"=>""],
            ["name" => "Dip. Lucia Begoña Canales Barturen", "extension"=>""],
            ["name" => "Dip. Luis Vicente Aguilar Castillo", "extension"=>""],
            ["name" => "Dip. Luz Alicia Delfín Rodríguez", "extension"=>""],
            ["name" => "Dip. Miguel Guillermo Pintos Guillén", "extension"=>""],
            ["name" => "Dip. Miriam García Guzmán", "extension"=>""],
            ["name" => "Dip. Montserrat Ortega Ruiz", "extension"=>""],
            ["name" => "Dip. Nallely Mendoza Camarillo", "extension"=>""],
            ["name" => "Dip. Naomi Edith Gómez Santos", "extension"=>""],
            ["name" => "Dip. Omar Edmundo Blanco Martínez", "extension"=>""],
            ["name" => "Dip. Paul Martínez Marie", "extension"=>""],
            ["name" => "Dip. Rafael Gustavo Fararoni Magaña", "extension"=>""],
            ["name" => "Dip. Ramón Díaz Ávila ", "extension"=>""],
            ["name" => "Dip. Roberto Francisco San Román Solana", "extension"=>""],
            ["name" => "Dip. Tania María Cruz Mejía ", "extension"=>""],
            ["name" => "Dip. Tanya Carola Viveros Cházaro", "extension"=>""],
            ["name" => "Dip. Urbano Bautista Martínez", "extension"=>""],
            ["name" => "Dip. Valeria Méndez Moctezuma", "extension"=>""],
            ["name" => "Dip. Victoria Gutiérrez Pérez", "extension"=>""],
            ["name" => "Dip. Yanet González De la Cruz", "extension"=>""],
            ["name" => "Dirección de Asistencia Técnica Legislativa", "extension"=>""],
            ["name" => "Dirección de Auditoría y Revisión Financiera", "extension"=>""],
            ["name" => "Dirección de Normatividad Control y Seguimiento", "extension"=>""],
            ["name" => "Dirección de Recursos Humanos", "extension"=>""],
            ["name" => "Dirección de Recursos Materiales y Servicios Generales", "extension"=>""],
            ["name" => "Dirección de Registro Legislativo y Publicaciones Oficiales", "extension"=>""],
            ["name" => "Dirección de Servicios Jurídicos", "extension"=>""],
            ["name" => "Dirección de Tesorería", "extension"=>""],
            ["name" => "Dirección del Centro de Estudios para la Igualdad de Género y los Derechos Humanos", "extension"=>""],
            ["name" => "Equidad y Género", "extension"=>""],
            ["name" => "Inventarios", "extension"=>""],
            ["name" => "JUCOPO", "extension"=>""],
            ["name" => "Normatividad", "extension"=>""],
            ["name" => "Oficina de Biblioteca", "extension"=>""],
            ["name" => "Oficina de Oficialía de Partes", "extension"=>""],
            ["name" => "Oficina de Seguridad", "extension"=>""],
            ["name" => "Oficina de Servicios Médicos", "extension"=>""],
            ["name" => "Oficina del Sindicato", "extension"=>""],
            ["name" => "Órgano Interno", "extension"=>""],
            ["name" => "Presidencia", "extension"=>""],
            ["name" => "Secretaría de Fiscalización", "extension"=>""],
            ["name" => "Secretaría de Servicios Administrativos y Financieros", "extension"=>""],
            ["name" => "Secretaría de Servicios Legislativos", "extension"=>""],
            ["name" => "Secretaría General", "extension"=>""],
            ["name" => "Servicio de fotocopiado", "extension"=>""],
            ["name" => "Servicio Médico", "extension"=>""],
            ["name" => "Subcontraloría Interna", "extension"=>""],
            ["name" => "Subdirección de Servicios Jurídicos", "extension"=>""],
            ["name" => "Unidad de Transparencia", "extension"=>""],
        ];



        foreach ($departamentos as $departamento) {
            DepartamentoCongreso::create($departamento);
        }
    }
}
